name: Build & Deploy Backend

on:
  push:
    branches: [main-stable]

env:
  REGISTRY: "registry.digitalocean.com/hale-project"
  IMAGE_NAME: "backend-app"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build container image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DO Container Registry
        run: |
          docker tag $IMAGE_NAME:latest $REGISTRY/$IMAGE_NAME:latest
          docker push $REGISTRY/$IMAGE_NAME:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            docker pull registry.digitalocean.com/hale-project/backend-app:latest
            docker stop hale-be-container || true
            docker rm hale-be-container || true
            docker run -d --name hale-be-container \
              -p 5000:5000 \
              --restart unless-stopped \
              -e PORT=5000 \
              -e MONGO_URI="${{ secrets.MONGO_URI }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e JWT_EXPIRE=24h \
              -e FRONTEND_URL=https://de-cora.com \
              -e EMAIL_FROM_NAME="Henderson Design Group" \
              -e EMAIL_FROM=hendersongroupnotify@gmail.com \
              -e EMAIL_USER=hale.henderson.alia.project@gmail.com \
              -e EMAIL_PASSWORD=nzbiyccrmtuvpxpb \
              -e EMAIL_REPLY_TO=aloha@henderson.house \
              -e BREVO_API_KEY=${{ secrets.BREVO_API_KEY }} \
              -e ADMIN_EMAIL="gustianggara@henderson.house;almer@henderson.house;madeline@henderson.house" \
              -e TEST_EMAIL=putra.a.gusti.anggara@gmail.com \
              -e SPACES_KEY=${{ secrets.SPACES_KEY }} \
              -e SPACES_SECRET="${{ secrets.SPACES_SECRET }}" \
              -e SPACES_ENDPOINT=https://hale-project.sfo3.digitaloceanspaces.com \
              -e SPACES_BUCKET=hale-project \
              -e SPACES_REGION=sfo3 \
              -e QUICKBOOKS_CLIENT_ID=${{ secrets.QUICKBOOKS_CLIENT_ID }} \
              -e QUICKBOOKS_CLIENT_SECRET=${{ secrets.QUICKBOOKS_CLIENT_SECRET }} \
              -e QUICKBOOKS_REDIRECT_URI=https://de-cora.com/api/quickbooks/callback \
              -e QUICKBOOKS_ENVIRONMENT=production \
              -e CHROME_BIN=/usr/bin/chromium-browser \
              -e CHROME_PATH=/usr/lib/chromium/ \
              -e PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
              -e PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser \
              registry.digitalocean.com/hale-project/backend-app:latest
