// models/Order.js
// ✅ PATCH: tambah proposalNumber di order level (bukan per-product)
//   Format: Hen-[ClientCode]-[6char] e.g. Hen-KIR-4f8a2c
//   Generated by CustomProductManager on mount, persisted via PUT /api/orders/:id

const mongoose = require('mongoose');

const orderSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },

  // ✅ NEW: proposal number at order level — 1 project = 1 number
  proposalNumber: {
    type: String,
    default: null
  },
  proposalQbId:      { type: String, default: null },
  proposalQbSyncedAt:{ type: Date,   default: null },

  customFloorPlan: {
    filename: String,
    contentType: String,
    data: Buffer,
    url: String,
    key: String,
    size: Number,
    notes: String,
    uploadedAt: Date
  },

  packageType: {
    type: String,
    enum: ['investor', 'custom', 'library'],
    default: 'investor'
  },

  clientInfo: {
    name: String,
    unitNumber: String,
    floorPlan: String
  },

  selectedPlan: {
    id: String,
    title: String,
    description: String,
    image: String,
    details: [String],
    clientInfo: {
      name: String,
      unitNumber: String,
      floorPlan: String
    }
  },

  Package: String,

  installationDate: String,
  installationNotes: String,

  selectedProducts: [{
    _id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Product'
    },
    product_id: String,
    name:       String,
    category:   String,

    package: {
      type: String,
      enum: ['', 'Lani', 'Nalu', 'Mainland'],
      default: ''
    },

    spotName:   String,
    quantity: {
      type: Number,
      default: 1
    },
    unitPrice:  Number,
    finalPrice: Number,
    vendor: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Vendor',
      required: false
    },
    sourceType: {
      type: String,
      enum: ['library', 'manual'],
      default: 'manual'
    },
    isEditable: {
      type: Boolean,
      default: true
    },

    selectedOptions: {

      // ── General Info ──
      sidemark:          String,
      group:             String,
      tags:              [String],
      itemClass:         String,
      cfaSampleApproval: String,
      vendorDescription: String,

      // ── Product spec ──
      finish:    String,
      fabric:    String,
      size:      String,
      insetPanel:String,

      woodFinish:  { type: String, default: '' },
      others:      { type: [String], default: [] },

      // ── Images ──
      image:    String,
      images:   [String],
      links:    [String],

      // ── Descriptions ──
      specifications:    String,
      notes:             String,

      // ── Shipping ──
      shipToVendorId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Vendor',
        required: false,
        default: null,
      },
      shipToName:          String,
      shippingStreet:      String,
      shippingCity:        String,
      shippingState:       String,
      shippingPostalCode:  String,
      shippingCountry:     String,
      shipToPhone:         String,

      // ── Install Binder ──
      poNumber:          String,
      vendorOrderNumber: String,
      trackingInfo:      String,
      deliveryStatus:    String,
      installerNotes:    String,

      // ── Status Report ──
      room:                    String,
      statusCategory:          String,
      proposalNumber:          { type: String, default: null }, // kept for legacy compat
      shipTo:                  String,
      orderDate:               String,
      expectedShipDate:        String,
      expectedArrivalDate:     String,
      dateReceived:            String,
      dateInspected:           String,
      estimatedDeliveryDate:   String,
      shippingCarrier:         String,
      orderStatus:             String,
      nextStep:                String,
      nextStepDate:            String,
      warehouseReceivingNumber:String,

      // ── Pricing — Purchase Cost ──
      units:             String,
      msrp:              Number,
      discountPercent:   Number,
      netCostOverride:   Number,
      noNetPurchaseCost: Boolean,
      discountTaken:     String,
      shippingCost:      Number,
      otherCost:         Number,

      // ── Pricing — Selling Cost ──
      markupPercent:         Number,
      shippingMarkupPercent: Number,
      otherMarkupPercent:    Number,
      depositPercent:        Number,
      vendorDepositPercent:  Number,
      salesTaxRate:          Number,

      // ── Pricing — Taxable flags ──
      taxableCost:           { type: Boolean, default: true },
      taxableMarkup:         { type: Boolean, default: true },
      taxableShippingCost:   { type: Boolean, default: true },
      taxableShippingMarkup: { type: Boolean, default: true },
      taxableOtherCost:      { type: Boolean, default: true },
      taxableOtherMarkup:    { type: Boolean, default: true },

      // ── Uploaded images ──
      uploadedImages: [{
        filename:    String,
        contentType: String,
        data:        Buffer,
        url:         String,
        key:         String,
        size:        Number,
        uploadedAt: {
          type: Date,
          default: Date.now
        }
      }],

      // ── Custom attributes ──
      customAttributes: {
        type: Map,
        of: mongoose.Schema.Types.Mixed,
        default: new Map()
      }
    },

    placement: {
      spotKey: String,
      coordinates: {
        x:        Number,
        y:        Number,
        width:    Number,
        height:   Number,
        rotation: { type: Number, default: 0 }
      }
    }
  }],

  occupiedSpots: {
    type: Map,
    of: {
      furnitureId:          String,
      label:                String,
      area:                 String,
      coordinates:          mongoose.Schema.Types.Mixed,
      originalCoordinates:  mongoose.Schema.Types.Mixed,
      rotation:             { type: Number, default: 0 },
      isPlaced:             Boolean,
      sourceConfig:         String,
      sourceSpot:           String,
      product: { type: mongoose.Schema.Types.ObjectId, ref: 'Product' }
    },
    default: {}
  },

  status: {
    type: String,
    enum: ['ongoing', 'completed', 'confirmed', 'cancelled', 'review'],
    default: 'ongoing'
  },

  step: {
    type: Number,
    default: 1
  },

  proposalVersions: [{
    version:   Number,
    notes:     String,
    createdAt: Date,
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    }
  }],

  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now }
});

orderSchema.pre('save', function(next) {
  this.updatedAt = Date.now();
  next();
});

module.exports = mongoose.model('Order', orderSchema);